# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

Assignment 1: Array Creation and Manipulation
Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [1]:

import numpy as np

In [2]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20
arr = np.random.randint(1,21, size=(5,5)) # use random int function
print(arr)

# Replace all the elements in the third column with 1.
arr[: ,2] = 1
print(arr)




[[ 9 11  6  3  6]
 [ 9  8 19 12 10]
 [ 6 11  4  8  4]
 [17 10 13  7 20]
 [17  6  9  5 11]]
[[ 9 11  1  3  6]
 [ 9  8  1 12 10]
 [ 6 11  1  8  4]
 [17 10  1  7 20]
 [17  6  1  5 11]]


In [3]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16.
arr2 = np.arange(1,17).reshape(4,4)
print(arr2)
# Replace the diagonal elements with 0
np.fill_diagonal(arr2,0)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


Assignment 2: Array Indexing and Slicing
Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [4]:
# Create a NumPy array of shape (6, 6) with values from 1 to 36. 
arr3 = np.arange(1,37).reshape(6,6)
print(arr3)
# Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
print(arr3[2:5,1:4])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [5]:
# Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border
arr4 = np.random.randint(1,26, size=(5,5))
print(arr4)

# Concatenate function
# np.concatenate((array1, array2), axis=0)
border_elements = np.concatenate((arr4[0, :], arr4[-1, :], arr4[1:-1, 0], arr4[1:-1, -1]))
print("Border elements:")
print(border_elements)





[[ 9  3 25 12 19]
 [23  5 17  6  3]
 [12  1 19  7 13]
 [12 12  8  2 20]
 [23  6 21 21 21]]
Border elements:
[ 9  3 25 12 19 23  6 21 21 21 23 12 12  3 13 20]


Assignment 3: Array Operations
Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [6]:
# Create two NumPy arrays of shape (3, 4) filled with random integers. 
# Perform element-wise addition, subtraction, multiplication, and division.
arr5 = np.random.randint(1,13, size=(3,4))
arr6 = np.random.randint(1,13, size=(3,4))
print(arr5 + arr6)
print(arr5 - arr6)
print(arr5 * arr6)
print(arr5 / arr6)



[[14  4 15 14]
 [12 14  7 13]
 [10 15 11  2]]
[[-8  0  7  8]
 [ 6  0  5 -7]
 [ 0 -5 -5  0]]
[[33  4 44 33]
 [27 49  6 30]
 [25 50 24  1]]
[[0.27272727 1.         2.75       3.66666667]
 [3.         1.         6.         0.3       ]
 [1.         0.5        0.375      1.        ]]


In [7]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
arr7= np.arange(1,17).reshape(4,4)
print(arr7)
row_sum = np.sum(arr7, axis=1) # ROW SUM
column_sum = np.sum(arr7, axis=0) # COLUMN SUM
print(row_sum)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[10 26 42 58]


Assignment 4: Statistical Operations
Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [8]:
# Create a NumPy array of shape (5, 5) filled with random integers. 
# Compute the mean, median, standard deviation, and variance of the array.
arr8 = np.random.randint(1,26, size=(5,5))
mean = np.mean(arr8)
print(mean)
median = np.median(arr8)
print(median)
std_dev = np.std(arr8)
variance = np.var(arr8)


11.16
10.0


In [9]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9. 
# Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).
arr9 = np.arange(1,10).reshape(3,3)
mean = np.mean(arr9)
std_dev=np.std(arr9)
norm = (arr9-mean)/std_dev
print(norm)

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [10]:
# 1. Create a NumPy array of shape (3, 3) filled with random integers. 
# Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
arr10 = np.random.randint(1,10, size=(3,3))
row_array = np.random.randint(1, 11, size=(3,))

arr11 = arr10 + row_array
print(arr11)

[[ 5 13 11]
 [10 12 13]
 [12 18 18]]
