Numpy Library
NumPy, short for Numerical Python, serves as a fundamental library for scientific computing in Python.
It introduces powerful tools for working with arrays, matrices, and mathematical functions.

In [2]:
# installing numpy via jupyter lab
!pip install numpy

Looking in indexes: https://artifactory.airbus.corp/artifactory/api/pypi/r-airbus-pypi-virtual/simple


In [3]:
import numpy as np


In [4]:
#creating 1D Array
arr1 = np.array([1,2,3,4])
print(arr1)


[1 2 3 4]


In [5]:
print(type(arr1))

<class 'numpy.ndarray'>


In [9]:
print(arr1.shape) #gives rows and columns 

(4,)


In [12]:
# Transforming a 1D array to 2D array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) #reshape arr2 to 1 row and 5 column 2d array


array([[1, 2, 3, 4, 5]])

In [14]:
# Creating 2d array 
arr3 = np.array([[1,2,3,4,5]]) # use nested list
arr3.shape

(1, 5)

In [15]:
# 2D Array
arr4 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr4)
print(arr4.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [22]:
#Arange function (Range start, Range end(Not inclusive), Step size)
arr5 = np.arange(0,12,2)
print(arr5)


[ 0  2  4  6  8 10]


In [21]:
# reshape it to a 2D array

arr5 = np.arange(0,12,2).reshape(6,1)
print(arr5)

[[ 0]
 [ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]]


In [26]:
# ones function (row, col) > will create a 2d array with element = 1
#*** Use a tuple to define rows and cols 
onearr = np.ones((3,2))
print(onearr)
xeroarr = np.zeros((3,2))
print(xeroarr)
# identity Matrix > Only diagonal elements 1
np.eye(4)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
# General attributes of Numpy

arr = np.array([[1,2,3,4],[5,6,7,8]])

print("\nArray : ", arr)
print("\nShape : ", arr.shape)
print("\nNUmber of Dimensions : ", arr.ndim)
print("\nSize (no of elements): ", arr.size)
print("\nDataType:", arr.dtype)
print("\nItemSize(in bytes) : ", arr.itemsize)


Array :  [[1 2 3 4]
 [5 6 7 8]]

Shape :  (2, 4)

NUmber of Dimensions :  2

Size (no of elements):  8

DataType: int64

ItemSize(in bytes) :  8


In [30]:
# Numpy Vectorized Ops
arrA = np.array([1,2,3,4,5])
arrB = np.array([10,20,30,40,50])


In [32]:
# Element wise addition
print(arrA + arrB)
# eLE WISE Substraction
print(arrA - arrB)
# Same for Multiply and Division



[11 22 33 44 55]
[ -9 -18 -27 -36 -45]


In [36]:
# Math functions
arrU = np.array([1,2,3,4,5])
print(np.sqrt(arrU)) # Squareroot
print(np.exp(arrU)) # Exponential
print(np.sin(arrU)) # sine
print(np.log(arrU))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [41]:
#array Slicing and Indexing

arrS = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arrS)

print(arrS[0][0]) # indexing is 0 based
print(arrS[1:,2:]) # Slicing





[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
1
[[ 8  9 10]
 [13 14 15]]


In [43]:
# Slicing 7,8,12,13
print(arrS[1:,1:3])

[[ 7  8]
 [12 13]]


In [44]:
# Modify arr elements
arrS[0,0] =17
print(arrS)

[[17  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


PRACTICAL Application 


In [46]:
# Statistical Concept
# NORMALISATION > Mean = 0 , Std Deviation = 1

arrM = np.array([1,2,3,4])

mean = np.mean(arrM)
st_dev = np.std(arrM)

normalized = (arrM - mean) /st_dev

print(arrM)
print(normalized)



[1 2 3 4]
[-1.34164079 -0.4472136   0.4472136   1.34164079]


In [48]:
# calculating Mean Median Mode
data = np.array([1,2,3,4,5,6,7,8,9,10])

mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)

print(mean)
print(median)
print(variance)
print(std_dev)

5.5
5.5
8.25
2.8722813232690143


In [53]:
# Logical Opertions
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[data>5] # logical ops
data[(data>=5) & (data<=8)]


array([5, 6, 7, 8])